<?php

namespace App\Repositories\Admin;

use App\Models\AttributeModel;
use App\Repositories\BaseRepository;

class AttributeRepository extends BaseRepository
{

    public function getModel() {
        return AttributeModel::class;
    }

    public function getAllAttribute()
    {
        return $this->getAll(); // TODO: Change the autogenerated stub
    }

    public function createAttribute($attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function findAttributeById($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    public function updateAttribute($id, $attributes = [])
    {
        return parent::update($id, $attributes); // TODO: Change the autogenerated stub
    }

    public function deleteAttribute($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
