<?php
namespace App\Repositories\Admin;

use App\Models\Category;
use App\Repositories\BaseRepository;

class CategoryRepository extends BaseRepository {

    public function getModel() {
        return Category::class;
    }

    public function getAllCategory()
    {
        return $this->getAll(); // TODO: Change the autogenerated stub
    }

    public function createCategory($attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function findCategoryById($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    public function updateCategory($id, $attributes = [])
    {
        return parent::update($id, $attributes); // TODO: Change the autogenerated stub
    }

    public function deleteCategory($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
